"""Validate every registry entry and regenerate data/registry/CATALOGUE.md.

Usage: python scripts/data/validate_registry.py [--no-catalogue]
Exit code 1 if any entry has an error.
"""
import argparse
import sys

import _bootstrap  # noqa: F401
from asal import paths, registry


def fmt(v):
    if isinstance(v, bool):
        return "yes" if v else "no"
    return str(v)


def catalogue(entries: dict, shared: dict) -> str:
    lines = [
        "# Asal dataset catalogue",
        "",
        "Generated by `scripts/data/validate_registry.py` from `data/registry/*.yaml`. Do not edit by hand.",
        "",
        "`provider` figures are claims by the provider (or a secondary source) and are not verified by Asal.",
        "Only entries with `inspected = yes` have Asal-measured values.",
        "",
        "| id | name | roles | licence (basis) | commercial | redistribution | MT | religious | inspected | approved |",
        "|---|---|---|---|---|---|---|---|---|---|",
    ]
    for eid, e in entries.items():
        lic = e["license"]
        lines.append(
            f"| `{eid}` | {e['name']} | {', '.join(e['roles'])} | {lic['corpus_license']} ({lic['license_basis']}) | "
            f"{fmt(lic['commercial_use'])} | {fmt(lic['redistribution'])} | {fmt(e['provenance']['machine_translated'])} | "
            f"{fmt(e['provenance']['religious_text'])} | {fmt(e['status']['inspected'])} | {fmt(e['status']['approved_for_training'])} |")
    lines += ["", "## Shared upstreams (do not add these corpora's sizes together)", ""]
    for up, ids in shared.items():
        lines.append(f"- **{up}**: {', '.join(f'`{i}`' for i in ids)}")
    lines += ["", "## Provider-reported sizes", "", "| id | figure | value | claim source |", "|---|---|---|---|"]
    for eid, e in entries.items():
        pr = e["size"]["provider_reported"]
        for k, v in pr.items():
            if k != "claim_source":
                lines.append(f"| `{eid}` | {k} | {v} | {pr.get('claim_source', 'unknown')} |")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--no-catalogue", action="store_true")
    args = ap.parse_args()
    report = registry.validate()
    for f in report.findings:
        if f.level != "info":
            print(f"[{f.level}] {f.entry}: {f.rule}: {f.message}")
    infos = sum(1 for f in report.findings if f.level == "info")
    print(f"{len(report.entries)} entries valid, {len(report.errors)} errors, {infos} info notes")
    if not args.no_catalogue and not report.errors:
        out = paths.REGISTRY_DIR / "CATALOGUE.md"
        out.write_text(catalogue(report.entries, registry.shared_upstreams(report.entries)), encoding="utf-8")
        print(f"wrote {out.relative_to(paths.ROOT)}")
    return 1 if report.errors else 0


if __name__ == "__main__":
    sys.exit(main())
